// <auto-generated />
using System;
using EnergyOptimizer.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnergyOptimizer.Infrastructure.Migrations
{
    [DbContext(typeof(EnergyDbContext))]
    [Migration("20251126212413_FixRealToFloat")]
    partial class FixRealToFloat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnergyOptimizer.Core.Entities.AI_Analysis.AIMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageCost")
                        .HasPrecision(10, 4)
                        .HasColumnType("float(10)");

                    b.Property<double>("AverageResponseTimeMs")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<int>("CacheHits")
                        .HasColumnType("int");

                    b.Property<int>("CacheMisses")
                        .HasColumnType("int");

                    b.Property<int>("FailedRequests")
                        .HasColumnType("int");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SuccessfulRequests")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalRequests")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MetricType");

                    b.HasIndex("Timestamp");

                    b.ToTable("AIMetrics");
                });

            modelBuilder.Entity("EnergyOptimizer.Core.Entities.AI_Analysis.AnalysisInsight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalysisId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsightText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.HasIndex("Priority");

                    b.ToTable("AnalysisInsights");
                });

            modelBuilder.Entity("EnergyOptimizer.Core.Entities.AI_Analysis.ConsumptionPrediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("ActualConsumptionKWh")
                        .HasPrecision(12, 2)
                        .HasColumnType("float(12)");

                    b.Property<double>("ConfidenceScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("float(5)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PredictedConsumptionKWh")
                        .HasPrecision(12, 2)
                        .HasColumnType("float(12)");

                    b.Property<DateTime>("PredictionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PredictionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PredictionDate");

                    b.ToTable("ConsumptionPredictions");
                });

            modelBuilder.Entity("EnergyOptimizer.Core.Entities.AI_Analysis.DetectedAnomaly", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ActualValue")
                        .HasPrecision(10, 4)
                        .HasColumnType("float(10)");

                    b.Property<int?>("AnalysisId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AnomalyTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Deviation")
                        .HasPrecision(10, 4)
                        .HasColumnType("float(10)");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<double>("ExpectedValue")
                        .HasPrecision(10, 4)
                        .HasColumnType("float(10)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<string>("PossibleCauses")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResolutionNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.HasIndex("DetectedAt");

                    b.HasIndex("DeviceId");

                    b.HasIndex("IsResolved", "Severity");

                    b.ToTable("DetectedAnomalies");
                });

            modelBuilder.Entity("EnergyOptimizer.Core.Entities.AI_Analysis.EnergyAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AnalysisDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AnalysisType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DevicesAnalyzed")
                        .HasColumnType("int");

                    b.Property<string>("FullResponse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalConsumptionKWh")
                        .HasPrecision(12, 2)
                        .HasColumnType("float(12)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisDate");

                    b.HasIndex("AnalysisType");

                    b.HasIndex("PeriodStart", "PeriodEnd");

                    b.ToTable("EnergyAnalyses");
                });

            modelBuilder.Entity("EnergyOptimizer.Core.Entities.AI_Analysis.EnergyRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionItems")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AnalysisId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("EstimatedSavingsKWh")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<double>("EstimatedSavingsPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("float(5)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ImplementedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsImplemented")
                        .HasColumnType("bit");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsImplemented");

                    b.HasIndex("Priority", "IsImplemented");

                    b.ToTable("EnergyRecommendations");
                });

            modelBuilder.Entity("EnergyOptimizer.Core.Entities.AI_Analysis.UsagePattern", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageConsumption")
                        .HasPrecision(10, 4)
                        .HasColumnType("float(10)");

                    b.Property<double>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("float(5)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PatternName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PatternType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("PeakConsumption")
                        .HasPrecision(10, 4)
                        .HasColumnType("float(10)");

                    b.Property<string>("PeakHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAt");

                    b.HasIndex("DeviceId", "IsActive");

                    b.HasIndex("ZoneId", "IsActive");

                    b.ToTable("UsagePatterns");
                });

            modelBuilder.Entity("EnergyOptimizer.Core.Entities.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeviceId");

                    b.HasIndex("IsRead");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("EnergyOptimizer.Core.Entities.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NumberOfRooms")
                        .HasColumnType("int");

                    b.Property<double>("TotalArea")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("EnergyOptimizer.Core.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("InstallationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("RatedPowerKW")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("EnergyOptimizer.Core.Entities.EnergyReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Current")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<decimal>("PowerConsumptionKW")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Voltage")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("Timestamp");

                    b.ToTable("EnergyReadings");
                });

            modelBuilder.Entity("EnergyOptimizer.Core.Entities.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("EnergyOptimizer.Core.Entities.AI_Analysis.AnalysisInsight", b =>
                {
                    b.HasOne("EnergyOptimizer.Core.Entities.AI_Analysis.EnergyAnalysis", "Analysis")
                        .WithMany("Insights")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("EnergyOptimizer.Core.Entities.AI_Analysis.DetectedAnomaly", b =>
                {
                    b.HasOne("EnergyOptimizer.Core.Entities.AI_Analysis.EnergyAnalysis", "Analysis")
                        .WithMany("Anomalies")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EnergyOptimizer.Core.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("EnergyOptimizer.Core.Entities.AI_Analysis.EnergyRecommendation", b =>
                {
                    b.HasOne("EnergyOptimizer.Core.Entities.AI_Analysis.EnergyAnalysis", "Analysis")
                        .WithMany("Recommendations")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("EnergyOptimizer.Core.Entities.AI_Analysis.UsagePattern", b =>
                {
                    b.HasOne("EnergyOptimizer.Core.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EnergyOptimizer.Core.Entities.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Device");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("EnergyOptimizer.Core.Entities.Alert", b =>
                {
                    b.HasOne("EnergyOptimizer.Core.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("EnergyOptimizer.Core.Entities.Device", b =>
                {
                    b.HasOne("EnergyOptimizer.Core.Entities.Zone", "Zone")
                        .WithMany("Devices")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("EnergyOptimizer.Core.Entities.EnergyReading", b =>
                {
                    b.HasOne("EnergyOptimizer.Core.Entities.Device", "Device")
                        .WithMany("EnergyReadings")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("EnergyOptimizer.Core.Entities.Zone", b =>
                {
                    b.HasOne("EnergyOptimizer.Core.Entities.Building", "Building")
                        .WithMany("Zones")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("EnergyOptimizer.Core.Entities.AI_Analysis.EnergyAnalysis", b =>
                {
                    b.Navigation("Anomalies");

                    b.Navigation("Insights");

                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("EnergyOptimizer.Core.Entities.Building", b =>
                {
                    b.Navigation("Zones");
                });

            modelBuilder.Entity("EnergyOptimizer.Core.Entities.Device", b =>
                {
                    b.Navigation("EnergyReadings");
                });

            modelBuilder.Entity("EnergyOptimizer.Core.Entities.Zone", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
